feat: added all basic features of backend
sjsouvik/shopwild pull request #3
Opened 2021-04-26 10:47 UTC by sjsouvik

2021-05-05 18:02 UTC, vinaybajjuri58 reviewed
Hey Souvik 
The code structure is pretty good nothing much changes to it 
But I suggest move paramHandlers to a seperate folder lto seperate it from controllers 
And remove commented line

2021-05-06 10:19 UTC, Jaynil1611 requested changes
- Great work @sjsouvik 
- Folder structure and file naming conventions are consistent
- Here are my few suggestions:

2021-05-06 10:19 UTC, Jaynil1611 commented on shopwild-backend/controllers/cart.js
> +      // });
Remove commented code

2021-05-06 10:19 UTC, Jaynil1611 commented on shopwild-backend/controllers/cart.js
> +    res.json({ cart });
Add status code as `res.status()` while sending responses across the source code

2021-05-06 10:19 UTC, Jaynil1611 commented on shopwild-backend/controllers/cart.js
> +    if (cart === null) {
No need to compare with null,
```suggestion
    if (cart) {
```

2021-05-06 10:19 UTC, Jaynil1611 commented on shopwild-backend/controllers/wishlist.js
> +exports.createUpdateWishlist = async (req, res) => {
Rename function as `createOrUpdate`

2021-05-06 10:19 UTC, Jaynil1611 commented on shopwild-backend/index.js
> +  .then(() => console.log("Connected to DB"))
use `async await` syntax

2021-05-06 10:19 UTC, Jaynil1611 commented on shopwild-backend/routes/user.js
> +  });
Extract this as a function in the user controller to make the code consistent and readable

2021-11-20 16:36 UTC, merged